version: "3.9"

services:
  frontend:
    image: fastapi-front:latest
    container_name: fastapi-frontend
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "5010:5010"
    depends_on:
      - backend
      - auth

  backend:
    image: fastapi-api:latest
    container_name: fastapi-backend
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5009:5009"
    depends_on:
      - auth

  auth:
    image: fastapi-auth:latest
    container_name: fastapi-auth
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "5002:5002"

volumes:
  frontend_data:
  backend_data:
  auth_data:
